### PR TITLE
Fix/cli multi args

### LINKED ISSUE #1: Using multiple arguments does not work as expected
Reproduction:
run `cypher-gen -s ", " -p "zyxwvutsrqponmlkjihgfedcba" hello world`

Expected: `19, 22, 15, 15, 12, 4, 12, 9, 15, 23`

 Actual: `16, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 8, 5, 12, 12, 15, 23, 15, 18, 12, 4`

### PR DESCRIPTION
**Pull request by Deadairx**
fixes #1 

This uses [Clap](https://docs.rs/clap/latest/clap/index.html) to manage arguments dynamically

also fixes a bug where capital letters in the pangram would cause a panic if the input included that letter

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -11,24 +20,22 @@ fn main() -> io::Result<()> {
...
     let mut pangram = "abcdefghijklmnopqrstuvwxyz";
 
-    if args[1] == "-p" || args[1] == "--pangram" {
-        pangram = args[2].as_str();
-        input_start = 3;
+    if let Some(p) = matches.get_one::<String>("pangram") {
+        pangram = p;
     }
 
+    println!("Pangram: {}", &pangram);
```
Comment (Deadairx) [inline src/main.rs:29]: **Thought(non-blocking)** I'm not totally sure if we want this to display, given the user should already know what the pangram is based on input.

**Review by Deadairx — COMMENTED** [review]
LGTM
